### ISSUE TITLE
v1 milestone tasks overview

### ISSUE THREAD

**Issue by Samir-Rashid** [Samir-Rashid/smartclip#1]
- [ ] battery: add connector, choose cell
- [ ] antenna: current antenna fine? possible to do something like airtag antenna?
- [ ] peripherals: not sure if anything else is needed. USB-C?
- [ ] routing, refine part selection 💀 
- [ ] make animation
- [ ] ESD protection, other product hardening

**Comment by bschan9228** [comment]
battery: probably some kind of 2032/button cell w/ coin cell holder or small lipo battery
antenna: chip antenna or pcb instead of u.fl antenna connector
peripherals: what are the current peripherals? i believe the current list was something like imu, leds, heartbeat? usb-c may not be useful since nrf52 doesn't have usb unless you use a bootloader, so it may only useful for recharging. jtag will probably be used for programming
routing: gl
animation: you got this
